CREATE SCHEMA IF NOT EXISTS portfolio_db;

DROP TABLE IF EXISTS PORTFOLIO_DB.TBL_COMPANY;
DROP TABLE IF EXISTS PORTFOLIO_DB.TBL_USER;

CREATE TABLE IF NOT EXISTS PORTFOLIO_DB.TBL_COMPANY (
  ID INT AUTO_INCREMENT  PRIMARY KEY
  ,NAME VARCHAR(250) NOT NULL
  ,ADDRESS VARCHAR(250)
  ,EMAIL VARCHAR(250)
  ,CREATED_AT DATE NOT NULL
  ,UPDATED_AT DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PORTFOLIO_DB.TBL_USER (
    ID INT AUTO_INCREMENT  PRIMARY KEY
    ,FIRST_NAME VARCHAR(250) NOT NULL
    ,MIDDLE_NAME VARCHAR(250) NOT NULL
    ,LAST_NAME VARCHAR(250) NOT NULL
    ,EMAIL VARCHAR(250) NOT NULL
    ,USERNAME VARCHAR(250) NOT NULL
    ,PASSWORD VARCHAR(250) NOT NULL
    ,CREATED_AT DATE NOT NULL
    ,UPDATED_AT DATE NOT NULL
);

--INSERT INTO PORTFOLIO_DB.TBL_COMPANY (ID, NAME, ADDRESS, EMAIL, CREATED_AT, UPDATED_AT) VALUES (1, 'Conversant', 'Main Street', 'conversant@example.com', '2022-01-01', '2022-01-01');
--INSERT INTO PORTFOLIO_DB.TBL_COMPANY (ID, NAME, ADDRESS, EMAIL, CREATED_AT, UPDATED_AT) VALUES (2, 'Accenture', 'Club Lane Dr', 'accenture@example.com', '2022-01-01', '2022-01-01');
