INSERT INTO PORTFOLIO_DB.TBL_COMPANY (ID, NAME, CREATED_AT, UPDATED_AT) VALUES (1, 'Conversant', '2022-01-01', '2022-01-01');
INSERT INTO PORTFOLIO_DB.TBL_COMPANY (ID, NAME, CREATED_AT, UPDATED_AT) VALUES (2, 'Accenture', '2022-01-01', '2022-01-01');
--INSERT INTO COMPANY (ID, NAME) VALUES (1, 'Conversant');
--INSERT INTO COMPANY (ID, NAME) VALUES (2, 'CFive');
--INSERT INTO COMPANY (ID, NAME) VALUES (2, 'Accenture');


