INSERT INTO PORTFOLIO_DB.TBL_COMPANY (ID, NAME, ADDRESS, EMAIL, CREATED_AT, UPDATED_AT) VALUES (1, 'Conversant', 'Main Street', 'conversant@example.com', '2022-01-01', '2022-01-01');
INSERT INTO PORTFOLIO_DB.TBL_COMPANY (ID, NAME, ADDRESS, EMAIL, CREATED_AT, UPDATED_AT) VALUES (2, 'Accenture', 'Club Lane Dr', 'accenture@example.com', '2022-01-01', '2022-01-01');
INSERT INTO PORTFOLIO_DB.TBL_COMPANY (ID, NAME, ADDRESS, EMAIL, CREATED_AT, UPDATED_AT) VALUES (3, 'B2W', 'Rio de Janeiro', 'b2w@example.com', '2022-01-01', '2022-01-01');
--INSERT INTO PORTFOLIO_DB.TBL_COMPANY (ID, NAME, ADDRESS, EMAIL, CREATED_AT, UPDATED_AT) VALUES (4, 'Google', 'San Francisco', 'google@example.com', '2022-01-01', '2022-01-01');
--INSERT INTO COMPANY (ID, NAME) VALUES (1, 'Conversant');
--INSERT INTO COMPANY (ID, NAME) VALUES (2, 'CFive');
--INSERT INTO COMPANY (ID, NAME) VALUES (2, 'Accenture');


